name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ arm64 ]

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build and push Docker image
      run: |
        docker build . --file WebApplication1/Dockerfile-arm64 --tag kanlai/kanpanle:arm64
        docker push kanlai/kanpanle:arm64
